<a href="https://colab.research.google.com/github/BustamJos3/learningTensorFlow/blob/DLAndTFFundamentals/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Most fundamental concepts
* intro to tensors
* getting info from tensors
* manipulating tensors
* Tensors & numpy
* using @tf.function (speed up regular py functions)
* use GPU/TPU with TF
* few exercises

## Intro to tensors

In [3]:
# import TF
import tensorflow as tf
print(tf.__version__)

2.9.2


In [4]:
# 1st tensor: tf.constant()
scalarTensor=tf.constant(7)
scalarTensor

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# check number of dimensions of a tensor
scalarTensor.ndim

0

In [8]:
# create a vector
vectorTensor=tf.constant([10]*2)
vectorTensor, vectorTensor.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>, 1)

In [10]:
# create a matrix
matrixTensor=tf.constant([[10, 7], [7, 10]])
matrixTensor, matrixTensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>, 2)

In [11]:
# using dtype parameter on tf.constant() to specify the data type
matrixTensor1=tf.constant([[10., 7.], 
                           [3., 2.], 
                           [8., 9.]], dtype=tf.float16)
matrixTensor1, matrixTensor1.ndim

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 3.,  2.],
        [ 8.,  9.]], dtype=float16)>, 2)

In [13]:
# creation of a tensor
tensor=tf.constant([[[1, 2, 3], 
                     [4, 5, 6]], 
                    [[7, 8, 9], 
                     [10, 11, 12]], 
                    [[13, 14, 15], 
                     [16, 17, 18]]])
tensor, tensor.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>, 3)

# What we've created so far:
* Scalar
* Vector
* Matrix
* Tensor