<a href="https://colab.research.google.com/github/BustamJos3/learningTensorFlow/blob/DLAndTFFundamentals/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Most fundamental concepts
* intro to tensors
* getting info from tensors
* manipulating tensors
* Tensors & numpy
* using @tf.function (speed up regular py functions)
* use GPU/TPU with TF
* few exercises

## Intro to tensors

In [2]:
# import TF
import tensorflow as tf
print(tf.__version__)

2.9.2


In [3]:
# 1st tensor: tf.constant()
scalarTensor=tf.constant(7)
scalarTensor

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check number of dimensions of a tensor
scalarTensor.ndim

0

In [5]:
# create a vector
vectorTensor=tf.constant([10]*2)
vectorTensor, vectorTensor.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>, 1)

In [6]:
# create a matrix
matrixTensor=tf.constant([[10, 7], [7, 10]])
matrixTensor, matrixTensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>, 2)

In [7]:
# using dtype parameter on tf.constant() to specify the data type
matrixTensor1=tf.constant([[10., 7.], 
                           [3., 2.], 
                           [8., 9.]], dtype=tf.float16)
matrixTensor1, matrixTensor1.ndim

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 3.,  2.],
        [ 8.,  9.]], dtype=float16)>, 2)

In [8]:
# creation of a tensor
tensor=tf.constant([[[1, 2, 3], 
                     [4, 5, 6]], 
                    [[7, 8, 9], 
                     [10, 11, 12]], 
                    [[13, 14, 15], 
                     [16, 17, 18]]])
tensor, tensor.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>, 3)

# What we've created so far:
* Scalar
* Vector
* Matrix
* Tensor

# Creating tensors with ```tf.Variable()```

In [9]:
# create the same tensor with tf.Variable as above
changeableTensor=tf.Variable([10, 7])
unchangeableTensor=tf.constant([10, 7])
changeableTensor, unchangeableTensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [11]:
# change 1 of the elements of changeableTensor
changeableTensor[0] = 7
changeableTensor

TypeError: ignored

In [12]:
# use method .assign
changeableTensor[0].assign(7)
changeableTensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [14]:
# try to change unchangeableTensor
unchangeableTensor[0].assign(7)
unchangeableTensor[0]

AttributeError: ignored

🔑**Note**: rarely in practice you will need to decide whether to use ```tf.constant``` or ```tf.Variable``` to create tensors, as TensorFlow does this for you. If in doubt, use ```tf.constant``` and change it later. 

# Creating random tensors
Are tensors of some arbitrary size which contain random numbers.

In [15]:
# create 2 random (but the same) tensors
random1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random1 = random1.normal(shape = (3, 2))
random2 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random2 = random2.normal(shape = (3, 2))

# are they equal?
random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [16]:
from operator import not_
# Shuffle a tensor (shuffle data so the inherent order does not affect learning)
not_shuffled= tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])
# Shuffle our tensor
tf.random.shuffle( not_shuffled )

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [17]:
# global random seed
tf.random.set_seed(42)
# operational random seed: it's a part of an operation
tf.random.shuffle( not_shuffled, seed=42 )

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

⚒**Exercise**: read through TensorFlow [docs](https://www.tensorflow.org/api_docs/python/tf/random/set_seed) on random seed generation and practice writing 5 random tensors and shuffle them
>1. If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
>2. If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
>3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
>4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [18]:
#set global seed
tf.random.set_seed(0)
#generate 5 tensors
tensor_container=[]
for i in range(5):
    tensor_container.append(tf.random.uniform( shape=(3, 3) ))
tensor_container

[<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.29197514, 0.20656645, 0.53539073],
        [0.5612575 , 0.4166745 , 0.80782795],
        [0.4932251 , 0.99812925, 0.69673514]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.5554141 , 0.22129297, 0.8649249 ],
        [0.77728355, 0.6451167 , 0.53036225],
        [0.01444101, 0.87350917, 0.4697218 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.1952138 , 0.7401732 , 0.4878018 ],
        [0.8753203 , 0.4071133 , 0.01454818],
        [0.7095418 , 0.36551023, 0.5808557 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.17513537, 0.3179742 , 0.8555474 ],
        [0.41725898, 0.23591995, 0.22561431],
        [0.59902835, 0.8288827 , 0.59770846]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.01353359, 0.09272444, 0.48645425],
        [0.7050798 , 0.35681212, 0.5552772 ],
        [0.6914648 , 0.42106915, 0.2079

### Other ways to make tensors
Very **similar to numpy**

In [19]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors
Diff, Numpy arrays vs TensorFlow arrays, tensors can be run on a GPU (much faster numerical computing)

In [21]:
# you can turn Numpy arrays into tensors
import numpy as np


In [22]:
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A, numpy_A.shape
# X = tf.constant(some_matrix), capital for matrix or tensor
# y = tf.constant(vector), non-capital for a vector

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32), (24,))

In [23]:
# product of shape elements must be equal to len of Numpy vector
A = tf.constant(numpy_A, shape=(2, 3, 4))
b = tf.constant(numpy_A)
A, 2*3*4, b

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 24,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting info from tensors
Being aware of the following attributes
* Shape
* Rank
* Axis or dimension
* Size



In [24]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros( shape = [ 2, 3, 4, 5 ] ) # 2 matrices of 3 matrices of 4 rows and 5 columns
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [26]:
rank_4_tensor.dtype, rank_4_tensor.shape, rank_4_tensor.ndim, tf.size( rank_4_tensor ).numpy() #last command to better readability .numpy

(tf.float32, TensorShape([2, 3, 4, 5]), 4, 120)

### Indexing tensors
Like python lists.

In [27]:
# get the 1st 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
# get the 1st element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
# the same as above can be obtained with this syntax
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
# create a rank_2_tensor (2 dimensions)
rank_2_tensor = tf.constant( [ [10, 7], 
                              [3, 4]] )
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [31]:
# get the last item of each row of our rank_2_tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

### Expanding tensors

In [32]:
# add extra dimension to the tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] #the previous info remains
rank_3_tensor #new axis @ the end

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [33]:
# alternative to newaxis
rank_3_tensor = rank_2_tensor[:,:, tf.newaxis] # add new axis on specific dimension
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [34]:
# the true expand process of a tensor
tf.expand_dims( rank_2_tensor, axis=-1 )#expand tensor on the last dim

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manipulating tensors (tensor ops)
**Basics ops**
$+,-,*,/$

In [35]:
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [36]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [37]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [38]:
# tf built-in module to multiply: tf.math. ; allow GPU sped up
tf.multiply( tensor, 10 )

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [39]:
tf.math.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

**Matrix Mutiplication**
Is one of the most common tensor operations

In [41]:
# Matrix multiplication: tf.linalg. built-in module
print(tensor)
# the function can be accesed without the call of the module
tf.linalg.matmul( tensor, tensor ), tf.matmul( tensor, tensor )

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>)

In [42]:
# MMul with python operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [43]:
# Tensor with shape (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [44]:
tf.matmul(X,Y)

InvalidArgumentError: ignored

In [47]:
Y.T

AttributeError: ignored

In [48]:
tf.transpose( Y )

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [49]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [50]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [51]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

**The dot product**

A part of matrix multiplication
* ```tf.matmul()```
* ```tf.tensordot()```

In [52]:
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [53]:
tf.tensordot(Y, tf.reshape(X, shape = (2, 3)), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]], dtype=int32)>

In [56]:
tf.tensordot(X, tf.reshape(Y, shape = (2, 3)), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

Generally, performing MatMul on tensors that does not line up, transpose will be used


### Changing the dataType of a tensor

In [57]:
# Create tensor with default dType
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [58]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [60]:
# Change float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D.dtype

tf.float16

In [61]:
E = tf.cast(C, dtype=tf.float16)
E.dtype

tf.float16


### Aggregating tensors

Condensing tensors from multiple values down to a smaller amount of values.

In [62]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [63]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Forms of aggregation
* Get the minimum
* Get the maximum
* The mean
* The sum of a tensor

In [82]:
# Random tensor with values from 0 to 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([86, 26, 65, 19, 42, 63, 80, 49, 74, 23, 50, 59, 88, 39, 15, 39, 62,
       38, 47, 94,  4, 77, 28, 66,  2, 15, 11, 43, 74, 34, 62, 83, 75, 53,
       31, 38, 23,  1, 20, 62, 27, 99, 54, 91, 86, 39, 78, 60, 96, 68])>

In [83]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [84]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [86]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [88]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2558>


⚒ **Exercise:** With what we've just learned, find the variance and standard deviation

In [89]:
# Find the variance
tf.reduce_variance(E)

AttributeError: ignored

In [91]:
import tensorflow_probability as tfp # acces to tf probability
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=721>

In [99]:
# Find the std
tf.math.reduce_std(tf.cast(E, dtype='float32')) # float32 is usually the standard

<tf.Tensor: shape=(), dtype=float32, numpy=26.86437>


### Find the positional max and the positional min